name: MLflow CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: membangun_model/conda.yaml
        activate-environment: prediksi_env
        python-version: 3.12

    - name: Run MLflow Project
      run: mlflow run membangun_model
